// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";
import { registerControllers } from "stimulus-vite-helpers";
const controllers = import.meta.globEager("./**/*_controller.js");
const oldControllers = import.meta.globEager("../../components/**/*_controller.js")
const compControllers = import.meta.globEager("../../views/components/**/*_controller.js")
registerControllers(application, controllers)
registerControllers(application, oldControllers)
registerControllers(application, compControllers)
