name: Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: pedro
          POSTGRES_PASSWORD: password
          POSTGRES_DB: boilerplate_test
        ports: ['5432:5432']
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: default
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: yarn

      - name: Install dependencies
        run: |
          sudo apt-get install -y -qq libvips
          yarn install --frozen-lockfile

      - name: Rubocop Check
        run: bundle exec rubocop

      - name: Run tests
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: pedro
          DB_PASS: password
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
        run: |
          bin/rails db:test:prepare
          bundle exec rspec
