name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: pedrosouza
          POSTGRES_PASSWORD: password
          POSTGRES_DB: boilerplate_test
        ports: ["5432:5432"]
      redis:
        image: redis
        ports: ["6379:6379"]
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: default
          bundler-cache: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9.1.4
          run_install: true

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt-get install -y -qq libvips
          pnpm install

      - name: Rubocop Check
        run: bundle exec rubocop

      - name: Run tests
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          RAILS_ENV: test
        run: |
          bin/rails db:test:prepare
          bundle exec rspec
